server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ @api;
    }

    location @api {
        proxy_pass http://app:8000;
        proxy_set_header Host $host; # Передаем оригинальный домен
        proxy_set_header X-Real-IP $remote_addr; # Передает реальный IP пользователя
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Передаем цепочку прокси-серверов (если их несколько)
        proxy_set_header X-Forwarded-Proto $scheme; # Передаем протокол (http или https), чтобы приложение знало, как генерировать ссылки
        proxy_intercept_errors on; # Заставляет Nginx использовать свои error_page
    }
}